 cat docker-compose.yml
version: '2'

services:
  test-web-app:
    cpuset: "0"
    mem_limit: 512m
    image: test-web-app:latest
    ports:
    - "7000:80"
  nginxserv:
    image: yankus/docker-nginx:latest
    ports:
      - "80:80"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - /data:/data
     - ./nginx/log:/var/log/nginx
    depends_on:
     - test-web-app
    links:
      - test-web-app

root@rockbot:/home/yan/docker#
